spring.application.name=cinema-tickets

payment-service.protocol=http
payment-service.hostname=payment.local.uk
payment-service.port=8444
payment-service.url=${payment-service.protocol}://${payment-service.hostname}:${payment-service.port}

reservation-service.protocol=http
reservation-service.hostname=reservation.local.uk
reservation-service.port=8444
reservation-service.url=${reservation-service.protocol}://${reservation-service.hostname}:${reservation-service.port}
